export { default as Input } from './Input';
export { default as Button } from './Button';
export { default as Navigation } from './Navigation';
export { default as GamesPreview } from './GamesPreview';
export { default as Footer } from './Footer';
export { default as DifficultyLevel } from './DifficultyLevel';
export { default as Word } from './Word';
export { default as Result } from './Result';
export { default as Pagination } from './Pagination';
